const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const path = require('node:path');
const root = process.argv[2] || path.resolve(__dirname, '..');
const chat = fs.readFileSync(path.join(root, 'web/app/static/js/brachybot-chat-todo.js'), 'utf8');
const ui = fs.readFileSync(path.join(root, 'web/app/static/js/brachybot-ui-api.js'), 'utf8');
function extract(source, start, end) {
    const a = source.indexOf(start), b = source.indexOf(end, a + start.length);
    assert(a >= 0 && b > a);
    return source.slice(a, b);
}
const context = vm.createContext({window: {}, _chatLanguageForSession: () => 'zh'});
vm.runInContext(extract(chat, 'function _visualEvidenceFallbackResponse(', '\nfunction _visualResponseNeedsGroundedFallback('), context);
const report = [{url:'/report/a.png', target:'report', source:'report_artifact', visual_purpose:'explain'}];
const fallback = context._visualEvidenceFallbackResponse(report, 'case', 'zh', '剂量分布如何', 'V100=90.31%；D90=120.63 Gy。报告D90=118 Gy。');
assert(fallback.includes('V100=90.31%'));
assert(fallback.includes('报告D90=118'));
assert(fallback.includes('图像解读未完成'));
assert(!fallback.includes('标注位置'));
assert(!fallback.includes('没有解析出'));
const en = context._visualEvidenceFallbackResponse(report, 'case', 'en', '', 'D90=120.63 Gy');
assert(en.includes('interpretation did not complete'));
assert(!en.includes('marked captures'));
const locate = context._visualEvidenceFallbackResponse([{url:'/viewer.png', visual_purpose:'locate'}], 'case', 'zh');
assert(locate.includes('不能') || locate.includes('不会'));
const summaryContext = vm.createContext({_contentMetric:(metrics, names) => names.map(key=>metrics[key]).find(value=>value!==undefined)});
vm.runInContext(extract(ui, 'function _reportDoseContentSummary(', '\nfunction _sessionContentUnavailableMessage('), summaryContext);
const summary = summaryContext._reportDoseContentSummary({planning:{prescriptionGy:120}, metrics:{v100:90.31, d90:118, v200:0}, oarDose:[{d2cc:0},{d2cc:null},{}]}, {metrics:{D90:120.63}}, 'zh');
assert(summary.includes('V200=0 %'));
assert(summary.includes('D90=118 Gy'));
assert(summary.includes('不一致：D90'));
assert(summary.includes('1 个器官'));
assert(summary.includes('尚未填写：'));
assert(!summary.includes('V150=0'));
const missing = summaryContext._reportDoseContentSummary({}, {}, 'en');
assert(missing.includes('Not populated:'));
assert(missing.includes('0 organ'));
assert(chat.includes('[responseText, ...presentationMessages]'));
assert(chat.includes('[responseBody, presentation.userMessage]'));
assert.equal((chat.match(/opts\.visualContext\?\.preliminary_response \|\| ''/g)||[]).length, 4);
console.log('PASS: report explanation failure preserves facts, separates location, and audits populated dose fields without inventing missing values.');
