"""
dvh_curve_tool — Auto-generated Tool
======================================
Generated by BrachyBot Self-Evolution Engine (seed example).
Description: Compute a differential / cumulative DVH curve for a structure
mask over a 3D dose array, returned as JSON-friendly bin counts.

This tool is intentionally a seed/template — it shows the contract every
LLM-generated tool must follow. The ToolCodeWriter pipeline can be
exercised end-to-end by writing a similar file into this directory and
re-running the brain integration.
"""

import os
import json
import logging
import numpy as np
from typing import Dict, Any, Optional, List

from tool_factory import BaseTool, ToolResult

logger = logging.getLogger(__name__)


class DVHCurveTool(BaseTool):
    """Compute a cumulative DVH curve (dose-bin → fraction of structure)."""

    @property
    def name(self) -> str:
        return "dvh_curve"

    @property
    def description(self) -> str:
        return (
            "Compute a cumulative Dose-Volume Histogram (DVH) curve for a structure. "
            "Input: 3D dose array (numpy) and a structure mask (numpy). "
            "Output: bin_centers (Gy) and cumulative_fraction (0–1)."
        )

    @property
    def input_schema(self) -> Dict:
        return {
            "type": "object",
            "properties": {
                "dose_array":   {"type": "array",  "description": "3D dose distribution (numpy)"},
                "structure_mask": {"type": "array", "description": "3D binary structure mask (numpy)"},
                "max_dose":     {"type": "number", "description": "Max dose to include in curve (Gy)", "default": 200.0},
                "bin_count":    {"type": "integer", "description": "Number of bins in the DVH curve", "default": 200},
            },
            "required": ["dose_array", "structure_mask"],
        }

    @property
    def output_schema(self) -> Dict:
        return {
            "type": "object",
            "properties": {
                "bin_centers":         {"type": "array", "description": "Dose bin centers in Gy"},
                "cumulative_fraction": {"type": "array", "description": "Cumulative volume fraction (0–1)"},
                "d_min":  {"type": "number"},
                "d_mean": {"type": "number"},
                "d_max":  {"type": "number"},
                "structure_voxels":    {"type": "integer"},
            },
        }

    def _execute(self, **kwargs) -> ToolResult:
        dose = np.asarray(kwargs["dose_array"], dtype=np.float32)
        mask = np.asarray(kwargs["structure_mask"], dtype=bool)
        max_dose = float(kwargs.get("max_dose", 200.0))
        bin_count = int(kwargs.get("bin_count", 200))

        if dose.shape != mask.shape:
            return ToolResult(
                success=False,
                error=f"dose_array shape {dose.shape} != structure_mask shape {mask.shape}",
            )
        if bin_count < 2:
            return ToolResult(success=False, error="bin_count must be >= 2")

        structure_voxels = int(mask.sum())
        if structure_voxels == 0:
            return ToolResult(success=False, error="structure_mask is empty")

        d_vals = dose[mask]
        d_min = float(d_vals.min())
        d_max = float(d_vals.max())
        d_mean = float(d_vals.mean())

        # Cumulative DVH: for each dose threshold, fraction of structure >= that dose
        bin_edges = np.linspace(0.0, max(max_dose, d_max * 1.01), bin_count + 1)
        bin_centers = 0.5 * (bin_edges[:-1] + bin_edges[1:])
        cumulative = np.zeros(bin_count, dtype=np.float32)
        for i, edge in enumerate(bin_edges[:-1]):
            cumulative[i] = float((d_vals >= edge).sum()) / structure_voxels

        return ToolResult(
            success=True,
            data={
                "bin_centers": bin_centers.tolist(),
                "cumulative_fraction": cumulative.tolist(),
                "d_min": d_min,
                "d_mean": d_mean,
                "d_max": d_max,
                "structure_voxels": structure_voxels,
            },
            message=f"DVH curve computed: {structure_voxels} voxels, Dmax={d_max:.2f}Gy",
            metadata={
                "structure_voxels": structure_voxels,
                "d_min": d_min,
                "d_mean": d_mean,
                "d_max": d_max,
                "bin_count": bin_count,
            },
        )


# ---------------------------------------------------------------------
# How to register this tool with the BrachyBot tool registry
# ---------------------------------------------------------------------
# 1. Make sure tool_factory/auto_generated/__init__.py exports DVHCurveTool.
# 2. The ToolCodeWriter (brain/core/tool_code_writer.py) auto-loads every
#    tool in this directory on brain integration startup, so simply
#    dropping the file here is enough to expose the tool to the LLM.
# 3. To force-reload after editing, call:
#        from brain.integration.integration import initialize_brain_integration
#        bridge = initialize_brain_integration()
#        bridge.reload_auto_generated_tools()
# ---------------------------------------------------------------------


if __name__ == "__main__":
    # Demo / smoke test
    rng = np.random.default_rng(seed=42)
    dose = rng.uniform(0, 100, size=(32, 32, 32)).astype(np.float32)
    mask = rng.uniform(0, 1, size=(32, 32, 32)) > 0.7
    tool = DVHCurveTool()
    result = tool._execute(dose_array=dose, structure_mask=mask, bin_count=50)
    print(result.message)
    print("d_min=", result.metadata["d_min"])
    print("d_mean=", result.metadata["d_mean"])
    print("d_max=", result.metadata["d_max"])
    print("first 5 cumulative bins:", result.data["cumulative_fraction"][:5])
