"""Low-cost turn classification and execution policy.

This module is deliberately conservative.  It may bypass an expensive router
only for deterministic, low-risk requests.  Clinical execution and evidence
based medical advice keep the normal routing and review gates.
"""

from dataclasses import dataclass
import re
from typing import FrozenSet, Iterable, Optional


KNOWLEDGE_TOOLS: FrozenSet[str] = frozenset({
    "clinical_kb", "web_search", "web_fetch", "web_access",
    "ctv_model_catalog", "doc_reader",
})

UI_TOOLS: FrozenSet[str] = frozenset({
    "ui_controller", "ui_inspector", "ui_screenshot", "ui_annotate",
    "viewer_command", "auto_navigate", "query_metrics", "dvh_curve",
})

CLINICAL_TOOLS: FrozenSet[str] = frozenset({
    "ctv_model_catalog", "ctv_segmentation", "oar_segmentation",
    "trajectory_init", "trajectory_refine", "trajectory_planning",
    "seed_planning", "seed_planning_rule_based", "seed_planning_rl",
    "dose_engine", "dose_evaluation", "planning_pipeline",
    "clinical_kb", "safety_validator", "plan_quality_scorer",
    "oar_constraint_checker", "plan_refinement", "report_auto_fill",
    "report_generator", "query_metrics", "ui_screenshot",
})


@dataclass(frozen=True)
class LocalTurnPolicy:
    """Execution choices made before any remote model call."""

    intent: str
    complexity: str
    requires_review: bool
    use_router: bool
    use_completeness: bool
    allow_tools: Optional[FrozenSet[str]] = None


def _has_cjk(text: str) -> bool:
    return bool(re.search(r"[\u3400-\u4dbf\u4e00-\u9fff]", text or ""))


def _contains_any(text: str, phrases: Iterable[str]) -> bool:
    lowered = (text or "").lower()
    return any(phrase.lower() in lowered for phrase in phrases)


def classify_local_turn(message: str, pending_tumor_site: bool = False) -> LocalTurnPolicy:
    """Classify a turn without an LLM, using conservative intent boundaries."""
    text = str(message or "").strip()
    lower = text.lower()
    small_talk = {
        "你好", "您好", "嗨", "哈喽", "早上好", "下午好", "晚上好",
        "hi", "hello", "hey", "good morning", "good afternoon", "good evening",
        "谢谢", "感谢", "thanks", "thank you",
    }
    if re.sub(r"\s+", " ", lower).strip("!?.,，。！？ ") in small_talk or re.search(
        r"(?:介绍自己|你是谁|你能做什么|你可以做什么|使用说明)|"
        r"\b(?:introduce yourself|who are you|what can you do|how do i use)\b",
        lower,
    ):
        # The classifier only removes the remote router/tool overhead. The
        # answer itself is still generated by the configured LLM.
        return LocalTurnPolicy("small_talk", "low", False, False, False, frozenset())

    external = _contains_any(lower, (
        "deeprare", "github", "gitlab", "repository", "repo", "source code",
        "外部项目", "项目代码", "开源代码",
    ))
    # Segmentation is an execution request, not a generic knowledge query.
    # Keep the Chinese aliases as Unicode escapes because this module must
    # remain ASCII-safe even when deployed with a non-UTF-8 locale.
    segmentation = _contains_any(lower, (
        "ctv", "oar segmentation", "segment ctv", "segment oar", "segmentation",
        "\u5206\u5272", "\u6267\u884cctv\u5206\u5272", "\u6267\u884coar\u5206\u5272",
        "\u9776\u533a", "\u5371\u53ca\u5668\u5b98", "\u80bf\u7624\u90e8\u4f4d",
    ))
    # A site-only follow-up is actionable only after the agent explicitly
    # asked for the tumor site. This prevents a bare site name in a new case
    # from silently starting a clinical workflow.
    if pending_tumor_site and _contains_any(lower, (
        "pancreas", "pancreatic", "liver", "kidney", "lung", "colon", "prostate",
        "\u80f0\u817a", "\u809d", "\u80be", "\u80ba", "\u7ed3\u80a0", "\u524d\u5217\u817a",
    )):
        segmentation = True
    planning = _contains_any(lower, (
        "执行规划", "开始规划", "重新规划", "粒子植入规划", "治疗计划",
        "planning_pipeline", "brachytherapy plan", "treatment plan", "replan",
    ))
    clinical_advice = _contains_any(lower, (
        "临床", "指南", "处方剂量", "oar", "d90", "v100", "v150", "v200",
        "剂量限值", "治疗适应证", "clinical", "guideline", "prescription dose",
    ))
    ui = _contains_any(lower, (
        "viewer", "切片", "窗口", "放大", "缩小", "显示", "隐藏", "透明度",
        "颜色", "截图", "调节", "设置", "切换", "拖拽", "3d", "2d",
        "viewer", "slice", "zoom", "show", "hide", "opacity", "screenshot",
        "set", "adjust", "toggle", "drag",
    ))
    if segmentation:
        return LocalTurnPolicy("segmentation", "medium", True, False, True, CLINICAL_TOOLS)
    if planning:
        return LocalTurnPolicy("clinical_planning", "high", True, True, True, CLINICAL_TOOLS)
    if external:
        return LocalTurnPolicy("external_project_query", "low", True, True, True, frozenset({"web_search", "web_fetch", "web_access"}))
    if clinical_advice:
        return LocalTurnPolicy("clinical_knowledge", "medium", True, True, True, KNOWLEDGE_TOOLS)
    if ui:
        return LocalTurnPolicy("ui_control", "low", False, False, False, UI_TOOLS)
    return LocalTurnPolicy("knowledge_query", "low", False, False, False, KNOWLEDGE_TOOLS)


def filter_tool_schemas(tools, policy: Optional[LocalTurnPolicy]):
    """Keep only tools permitted by the local policy and current registry."""
    if not policy or policy.allow_tools is None:
        return tools
    allowed = policy.allow_tools
    return [
        item for item in (tools or [])
        if item.get("function", {}).get("name") in allowed
    ]
