"""
Tool Code Writer
================
Enables the agent to write new tool code, validate it,
and register it into the tool registry dynamically.
"""

import os
import re
import ast
import sys
import json
import logging
import importlib
from typing import Dict, List, Optional, Any

logger = logging.getLogger(__name__)

TOOL_FACTORY_DIR = os.path.join(
    os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
    "tool_factory",
)

TOOL_TEMPLATE = '''"""
{tool_name} — Auto-generated Tool
==================================
Generated by BrachyBot Self-Evolution Engine.
Description: {description}
"""

import os
import logging
import numpy as np
from dataclasses import dataclass
from typing import Dict, Any, Optional

from tool_factory.base import BaseTool, ToolResult

logger = logging.getLogger(__name__)


class {class_name}(BaseTool):
    """{description}"""

    name = "{tool_name}"
    description = "{description}"
    input_schema = {input_schema}
    output_schema = {output_schema}

    def _execute(self, **kwargs) -> ToolResult:
        """Execute the tool."""
        try:
{execute_body}
            return ToolResult(
                success=True,
                data=result,
                message="{tool_name} completed successfully",
                metadata={{"tool": "{tool_name}"}},
            )
        except Exception as e:
            logger.error(f"{tool_name} failed: {{e}}")
            return ToolResult(
                success=False,
                error=str(e),
                message=f"{tool_name} failed: {{e}}",
            )


if __name__ == "__main__":
    tool = {class_name}()
    result = tool.execute()
    print(json.dumps(result.to_dict(), indent=2, default=str))
'''


class ToolCodeWriter:
    """
    Generates, validates, and registers new tools dynamically.
    """

    def __init__(self, tool_registry=None):
        self.tool_registry = tool_registry
        self.generated_tools: List[Dict] = []
        self.tools_dir = os.path.join(TOOL_FACTORY_DIR, "auto_generated")
        os.makedirs(self.tools_dir, exist_ok=True)

    def generate_tool(self, name: str, description: str, category: str,
                      input_schema: Dict, output_schema: Dict,
                      execute_logic: str, class_name: str = None) -> Dict:
        """
        Generate a new tool from specification.

        Args:
            name: Tool name (snake_case)
            description: Tool description
            category: Tool category (subdirectory under tool_factory/)
            input_schema: Input parameter schema
            output_schema: Output schema
            execute_logic: Python code for _execute body (indented)
            class_name: Optional class name (auto-generated if not provided)
        """
        if not class_name:
            class_name = "".join(w.capitalize() for w in name.split("_")) + "Tool"

        code = TOOL_TEMPLATE.format(
            tool_name=name,
            description=description,
            class_name=class_name,
            input_schema=json.dumps(input_schema, indent=8),
            output_schema=json.dumps(output_schema, indent=8),
            execute_body=execute_logic,
        )

        validation = self._validate_code(code)
        if not validation["valid"]:
            return {
                "success": False,
                "error": f"Code validation failed: {validation['errors']}",
                "code": code,
            }

        tool_dir = os.path.join(TOOL_FACTORY_DIR, category)
        os.makedirs(tool_dir, exist_ok=True)

        file_path = os.path.join(tool_dir, f"{name}.py")
        with open(file_path, "w", encoding="utf-8") as f:
            f.write(code)

        tool_info = {
            "name": name,
            "class_name": class_name,
            "description": description,
            "category": category,
            "file_path": file_path,
            "code": code,
            "input_schema": input_schema,
            "output_schema": output_schema,
        }
        self.generated_tools.append(tool_info)
        logger.info(f"Tool generated: {name} -> {file_path}")
        return {"success": True, "tool": tool_info}

    def generate_tool_from_llm_spec(self, llm_spec: Dict) -> Dict:
        """
        Generate a tool from an LLM-produced specification.

        Expected LLM output format:
        {
            "name": "my_tool",
            "description": "...",
            "category": "dose_eval",
            "input_schema": {...},
            "output_schema": {...},
            "execute_logic": "    # code here\n    result = ..."
        }
        """
        required = ["name", "description", "category", "execute_logic"]
        missing = [k for k in required if k not in llm_spec]
        if missing:
            return {"success": False, "error": f"Missing fields: {missing}"}

        return self.generate_tool(
            name=llm_spec["name"],
            description=llm_spec["description"],
            category=llm_spec["category"],
            input_schema=llm_spec.get("input_schema", {}),
            output_schema=llm_spec.get("output_schema", {}),
            execute_logic=llm_spec["execute_logic"],
            class_name=llm_spec.get("class_name"),
        )

    def register_generated_tool(self, name: str) -> Dict:
        """Load and register a generated tool into the registry."""
        tool_info = None
        for t in self.generated_tools:
            if t["name"] == name:
                tool_info = t
                break
        if not tool_info:
            return {"success": False, "error": f"Generated tool not found: {name}"}

        try:
            file_path = tool_info["file_path"]

            if not os.path.exists(file_path):
                return {"success": False, "error": f"Tool file not found: {file_path}"}

            real_path = os.path.realpath(file_path)
            allowed_dir = os.path.realpath(TOOL_FACTORY_DIR)
            if not real_path.startswith(allowed_dir):
                return {"success": False, "error": "Tool file path is outside allowed directory"}

            spec = importlib.util.spec_from_file_location(name, file_path)
            if spec is None or spec.loader is None:
                return {"success": False, "error": "Failed to create module spec"}

            module = importlib.util.module_from_spec(spec)
            sys.modules[name] = module
            # REVIEW (SECURITY): `exec_module` runs arbitrary LLM-authored
            # Python in the host process. `_validate_code` only blocks a
            # deny-list of substrings (`eval(`, `__import__`, `exec(`, ...),
            # which is trivially evaded (e.g. `os.environ`, `urllib.request`,
            # `socket.gethostbyname`). A malicious or hallucinated tool spec
            # can therefore run anything as the server user. Production
            # deployment should require human approval before registering
            # each LLM-generated tool, sandbox execution (no `os`/`socket`/
            # `subprocess` in the exec namespace), and namespace `name` to
            # avoid shadowing real packages. NOT FIXED — requires sandbox
            # architecture; flagged for project security review.
            spec.loader.exec_module(module)
            tool_class = getattr(module, tool_info["class_name"])
            tool_instance = tool_class()

            if self.tool_registry:
                self.tool_registry.register(
                    name=name,
                    description=getattr(tool_instance, "description", tool_info.get("description", "")),
                    category=tool_info.get("category", "generated"),
                    parameters=getattr(tool_instance, "input_schema", {}) or {},
                    input_schema=json.dumps(getattr(tool_instance, "input_schema", {}) or {}, ensure_ascii=False),
                    output_schema=json.dumps(getattr(tool_instance, "output_schema", {}) or {}, ensure_ascii=False),
                    execute_fn=tool_instance.execute,
                )
                logger.info(f"Tool registered: {name}")
                return {"success": True, "message": f"Tool {name} registered"}
            else:
                return {"success": False, "error": "No tool registry available"}
        except Exception as e:
            logger.error(f"Failed to register tool {name}: {e}")
            return {"success": False, "error": str(e)}

    def _validate_code(self, code: str) -> Dict:
        """Validate generated Python code."""
        errors = []
        try:
            tree = ast.parse(code)
        except SyntaxError as e:
            return {"valid": False, "errors": [f"Syntax error: {e}"]}

        has_execute = False
        has_return = False
        for node in ast.walk(tree):
            if isinstance(node, ast.FunctionDef) and node.name == "_execute":
                has_execute = True
                for child in ast.walk(node):
                    if isinstance(child, ast.Return):
                        has_return = True

        if not has_execute:
            errors.append("No _execute method found")
        if not has_return:
            errors.append("No return statement in _execute")
        if "ToolResult" not in code:
            errors.append("ToolResult not used in code")

        dangerous_patterns = [
            ("__import__", "Dynamic import detected"),
            ("importlib", "importlib usage detected"),
            ("subprocess", "subprocess usage detected"),
            ("os.system", "os.system() detected"),
            ("os.popen", "os.popen() detected"),
            ("eval(", "eval() detected"),
            ("exec(", "exec() detected"),
            ("compile(", "compile() detected"),
            ("getattr(__builtins__", "Builtins access detected"),
            ("setattr(__builtins__", "Builtins modification detected"),
            ("__class__.__bases__", "Class manipulation detected"),
            ("__subclasses__", "Subclass enumeration detected"),
            ("globals()[", "Global namespace access detected"),
            ("sys.modules", "sys.modules manipulation detected"),
        ]
        for pattern, msg in dangerous_patterns:
            if pattern in code:
                errors.append(f"Dangerous pattern detected: {msg}")

        for node in ast.walk(tree):
            if isinstance(node, ast.Call):
                if isinstance(node.func, ast.Name) and node.func.id in ("eval", "exec", "compile"):
                    errors.append(f"Dangerous AST node: {node.func.id}() call detected")
                if isinstance(node.func, ast.Attribute):
                    if node.func.attr in ("system", "popen", "spawn") and isinstance(node.func.value, ast.Name):
                        if node.func.value.id in ("os", "subprocess"):
                            errors.append(f"Dangerous AST node: {node.func.value.id}.{node.func.attr}()")

        return {"valid": len(errors) == 0, "errors": errors}

    def list_generated_tools(self) -> List[Dict]:
        return [
            {
                "name": t["name"],
                "description": t["description"],
                "category": t["category"],
                "file_path": t["file_path"],
            }
            for t in self.generated_tools
        ]

    def get_tool_code(self, name: str) -> Optional[str]:
        for t in self.generated_tools:
            if t["name"] == name:
                return t["code"]
        return None
