"""
Communication Protocol for Multi-Agent System
==============================================
Defines the message format and agent roles for inter-agent communication.
Inspired by OpenCode's subagent architecture and AutoGPT's message passing.
"""

from dataclasses import dataclass, field
from enum import Enum
from typing import Any, Dict, List, Optional
import time
import uuid


class AgentRole(Enum):
    """Agent roles in the multi-agent system."""
    ROUTER = "router"
    PLANNER = "planner"
    CLINICAL_EXECUTOR = "clinical_executor"
    KNOWLEDGE = "knowledge"
    PLAN_REVIEWER = "plan_reviewer"
    FACT_CHECKER = "fact_checker"
    SAFETY_GUARDIAN = "safety_guardian"
    SYNTHESIZER = "synthesizer"
    USER = "user"  # Represents the user


class MessageType(Enum):
    """Types of messages exchanged between agents."""
    REQUEST = "request"           # Request for action
    RESPONSE = "response"         # Response to request
    FEEDBACK = "feedback"         # Feedback on results
    ALERT = "alert"               # Warning or error alert
    REVIEW = "review"             # Review result
    QUERY = "query"               # Information query
    NOTIFICATION = "notification" # Status update


class Priority(Enum):
    """Message priority levels."""
    LOW = 0
    NORMAL = 1
    HIGH = 2
    CRITICAL = 3


@dataclass
class AgentMessage:
    """Message exchanged between agents."""
    sender: AgentRole
    receiver: AgentRole
    message_type: MessageType
    content: Any
    metadata: Dict = field(default_factory=dict)
    priority: Priority = Priority.NORMAL
    message_id: str = field(default_factory=lambda: str(uuid.uuid4())[:8])
    timestamp: float = field(default_factory=time.time)
    parent_id: Optional[str] = None  # For request-response chains

    def to_dict(self) -> Dict:
        return {
            "message_id": self.message_id,
            "sender": self.sender.value,
            "receiver": self.receiver.value,
            "message_type": self.message_type.value,
            "content": self.content,
            "metadata": self.metadata,
            "priority": self.priority.value,
            "timestamp": self.timestamp,
            "parent_id": self.parent_id,
        }


@dataclass
class AgentResponse:
    """Standard response from an agent."""
    agent_role: AgentRole
    success: bool
    result: Any
    confidence: float = 0.8  # 0.0-1.0
    reasoning: str = ""      # Reasoning process
    suggestions: List[str] = field(default_factory=list)
    warnings: List[str] = field(default_factory=list)
    metadata: Dict = field(default_factory=dict)

    def to_dict(self) -> Dict:
        return {
            "agent_role": self.agent_role.value,
            "success": self.success,
            "result": self.result,
            "confidence": self.confidence,
            "reasoning": self.reasoning,
            "suggestions": self.suggestions,
            "warnings": self.warnings,
            "metadata": self.metadata,
        }


@dataclass
class RoutingDecision:
    """Decision made by the Router Agent."""
    intent: str                    # Identified intent
    complexity: str                # "low", "medium", "high"
    agents_needed: List[AgentRole] # Agents to involve
    requires_review: bool          # Whether quality review is needed
    context: Dict = field(default_factory=dict)
    reasoning: str = ""
    confidence: float = 0.8        # 0.0-1.0


@dataclass
class ExecutionPlan:
    """Plan generated by the Planner Agent."""
    steps: List[Dict]              # Execution steps
    parallel_groups: List[List[int]] = field(default_factory=list)  # Steps that can run in parallel
    estimated_time: float = 0.0
    reasoning: str = ""


@dataclass
class ReviewResult:
    """Result from a review agent."""
    reviewer: str                  # Reviewer name
    decision: str                  # "pass", "conditional", "reject", "escalate"
    score: float                   # 0-10
    concerns: List[str] = field(default_factory=list)
    suggestions: List[str] = field(default_factory=list)
    confidence: float = 0.7


@dataclass
class GateResult:
    """Result from quality gate."""
    passed: bool
    decision: str                  # "pass", "conditional", "reject", "escalate"
    reviews: List[ReviewResult] = field(default_factory=list)
    final_message: str = ""
    requires_human_review: bool = False
